# Generated by Django 2.2 on 2019-04-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('des3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='q_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
